const SET_ARTICLE = 'SET_ARTICLE';
const SET_ARTICLES = 'SET_ARTICLES';
const SET_TOTAL_RESULTS = 'SET_TOTAL_RESULTS';
const SET_PARAMS = 'SET_PARAMS';

export {
  SET_ARTICLE,
  SET_ARTICLES,
  SET_TOTAL_RESULTS,
  SET_PARAMS,
};
